// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Domain.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class Vehicle : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Vehicle"",""namespace"":""Domain.Events"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Plate"",""type"":""string""},{""name"":""Model"",""type"":""string""},{""name"":""ModelYear"",""type"":""int""},{""name"":""DateUpdateUtc"",""type"":[""null"",{""type"":""long"",""logicalType"":""timestamp-micros""}]}]}");
		private string _Id;
		private string _Plate;
		private string _Model;
		private int _ModelYear;
		private System.Nullable<System.DateTime> _DateUpdateUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Vehicle._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Plate
		{
			get
			{
				return this._Plate;
			}
			set
			{
				this._Plate = value;
			}
		}
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				this._Model = value;
			}
		}
		public int ModelYear
		{
			get
			{
				return this._ModelYear;
			}
			set
			{
				this._ModelYear = value;
			}
		}
		public System.Nullable<System.DateTime> DateUpdateUtc
		{
			get
			{
				return this._DateUpdateUtc;
			}
			set
			{
				this._DateUpdateUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Plate;
			case 2: return this.Model;
			case 3: return this.ModelYear;
			case 4: return this.DateUpdateUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Plate = (System.String)fieldValue; break;
			case 2: this.Model = (System.String)fieldValue; break;
			case 3: this.ModelYear = (System.Int32)fieldValue; break;
			case 4: this.DateUpdateUtc = (System.Nullable<System.DateTime>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
